#!/bin/sh
c_file="/tmp/grep_$( echo "$1 $2" | md5sum | cut -f1 -d' ').txt"
[ -s $c_file ] && cursor=$( cat $c_file ) || {
    cursor=0 
    echo "$( wc -l $1 | cut -f1 -d' ')">$c_file
}
tail -n +$cursor $1 | tee $c_file.tmp | egrep -q -m 1 "$2"
echo "$(( $( wc -l $c_file.tmp | cut -f1 -d' ' ) + $cursor ))">$c_file
rm -f $c_file.tmp
